= MemType Documentation
area0x33 <info@area0x33.com>
:icons: font
:data-uri:

[IMPORTANT]
====
*This documentation is under active development and discussion!*

If you find errors or omissions in this document, please don't hesitate to 
https://github.com/jim17/memtype/issues/new[submit an issue] or open a pull
request with a fix. We also encourage you to ask questions and discuss any 
aspects of the project by mailto:info@area0x33.com[email].
====


Welcome to the MemType documentation, here you'll learn everything about the 
MemType hardware, firmware, software tools and usage for any user level.


:toc:

== Introduction
// TODO Add a license section including license
Technically speaking the MemType is an open source `hardware password keeper`.
This means it is basically a device focused in securely `storing passwords` to prevent anyone
but the owner to access them. The `open source` part means that we share all the
software source files, hardware design files and documentation under the
<<license>> conditions.
